# General server settings
log_level: debug

# Redis configuration
redis:
  address: localhost:6379

ingress:
  rtmp_base_url: rtmp://localhost:1935/live
  whip_base_url: http://localhost:8080/whip

webhook:
  api_key: webhook_key
  urls: 
    - http://localhost:3000/api/livekit-webhook

keys:
  webhook_key: webhook_secret
  devkey: secret

